"""Removed the IMAGE URL in flights

Revision ID: 50bf22f8c8f9
Revises: 32fabe6e18ec
Create Date: 2026-06-08 15:54:03.211640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bf22f8c8f9'
down_revision: Union[str, None] = '32fabe6e18ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aircraft_seats_aircraft_id_fkey'), 'aircraft_seats', type_='foreignkey')
    op.create_foreign_key(None, 'aircraft_seats', 'aircraft', ['aircraft_id'], ['id'])
    op.alter_column('airports', 'best_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('airports', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('flights', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('airports', 'image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('airports', 'best_time',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'aircraft_seats', type_='foreignkey')
    op.create_foreign_key(op.f('aircraft_seats_aircraft_id_fkey'), 'aircraft_seats', 'aircraft', ['aircraft_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
