"""add_aircraft_seats_table

Revision ID: 8e73ea251568
Revises: e9a0de2c2c26
Create Date: 2026-05-30 13:59:23.594852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e73ea251568'
down_revision: Union[str, None] = 'e9a0de2c2c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('seat_class_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['seat_class_id'], ['seat_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircraft_seats')
    # ### end Alembic commands ###
