"""update promotions table schema for flexibility

Revision ID: db1a02535bf3
Revises: c66b208c40df
Create Date: 2026-05-28 16:33:18.979059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a02535bf3'
down_revision: Union[str, None] = 'c66b208c40df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('destination_code', sa.String(length=10), nullable=True))
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('promotions', 'destination_city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'destination_city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('promotions', 'destination_code')
    # ### end Alembic commands ###
