"""fix promotions valid_until to date and add updated_at

Revision ID: e9a0de2c2c26
Revises: db1a02535bf3
Create Date: 2026-05-28 19:32:47.404865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a0de2c2c26'
down_revision: Union[str, None] = 'db1a02535bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="valid_until::date"
    )
                
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               postgresql_using="valid_until::date"
    )
    op.drop_column('promotions', 'updated_at')
    # ### end Alembic commands ###
