"""add_success_and_is_admin_to_login_attempts

Revision ID: eaaeb1364590
Revises: 026439489ee9
Create Date: 2026-06-11 13:36:03.769903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaeb1364590'
down_revision: Union[str, None] = '026439489ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cancellations', 'refund_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.add_column('login_attempts', sa.Column('success', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('login_attempts', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_attempts', 'is_admin')
    op.drop_column('login_attempts', 'success')
    op.alter_column('cancellations', 'refund_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
