"""add_paymongo_support_to_payments_table

Revision ID: f9a2af1c3d18
Revises: ab21f2b08505
Create Date: 2026-06-09 16:45:03.341939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9a2af1c3d18'
down_revision: Union[str, None] = 'ab21f2b08505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method_type', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('checkout_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('external_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'external_metadata')
    op.drop_column('payments', 'checkout_url')
    op.drop_column('payments', 'payment_method_type')
    # ### end Alembic commands ###
